name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get Rodent / Build APK
      uses: Kivy-CN/actions-build-apk@v1
      with:
        buildozer_version: master
